//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTA_V_Suspend.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTA_V_Suspend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sürüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string About_Label_VersionHeader {
            get {
                return ResourceManager.GetString("About_Label_VersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string About_LabelAbout {
            get {
                return ResourceManager.GetString("About_LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yapımcı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string About_Version_Producer {
            get {
                return ResourceManager.GetString("About_Version_Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürdür benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string b_res {
            get {
                return ResourceManager.GetString("b_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askıya al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string b_sus {
            get {
                return ResourceManager.GetString("b_sus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap BKAAKCO_B_LOGO_48 {
            get {
                object obj = ResourceManager.GetObject("BKAAKCO_B_LOGO_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   İşlem kimliği (PID): benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string desc_id {
            get {
                return ResourceManager.GetString("desc_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string desc_status {
            get {
                return ResourceManager.GetString("desc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askıda geçen süre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string desc_time {
            get {
                return ResourceManager.GetString("desc_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bir sorun oluştu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun çalışmıyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string id_failed {
            get {
                return ResourceManager.GetString("id_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Askıya alma bittiğinde oyuna dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_BackToGame {
            get {
                return ResourceManager.GetString("Settings_Cbox_BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun içi kısayolu etkinleştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_EnableKey {
            get {
                return ResourceManager.GetString("Settings_Cbox_EnableKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 saniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_SuspendTime1 {
            get {
                return ResourceManager.GetString("Settings_Cbox_SuspendTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9 saniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_SuspendTime2 {
            get {
                return ResourceManager.GetString("Settings_Cbox_SuspendTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10 saniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_SuspendTime3 {
            get {
                return ResourceManager.GetString("Settings_Cbox_SuspendTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   11 saniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Cbox_SuspendTime4 {
            get {
                return ResourceManager.GetString("Settings_Cbox_SuspendTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Label_App {
            get {
                return ResourceManager.GetString("Settings_Label_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun içi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Label_Game {
            get {
                return ResourceManager.GetString("Settings_Label_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Label_Language {
            get {
                return ResourceManager.GetString("Settings_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kısayol tuşu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Label_Shortcut {
            get {
                return ResourceManager.GetString("Settings_Label_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askıya alma süresi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_Label_SuspendTime {
            get {
                return ResourceManager.GetString("Settings_Label_SuspendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Settings_LabelSettings {
            get {
                return ResourceManager.GetString("Settings_LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askıya almak için bekleniyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askıya alınamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string status_failed {
            get {
                return ResourceManager.GetString("status_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem askıya alındı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string status_success {
            get {
                return ResourceManager.GetString("status_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    sn benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
    }
}
